name: Get Citation Data

on: 
 page_build: 
 schedule:
  - cron:  '0 8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Reqs
      run: |
        sudo apt-get install python3-setuptools
        cd ./google_scholar_crawler
        pip3 install -r requirements.txt
    - name: Announce start of main.py
      run: echo ">>> running main.py at $(date)"
    - name: Run scholar crawler
      run: |
        cd ./google_scholar_crawler
        python3 main.py
      env: 
        GOOGLE_SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}
    - name: End py, start git
      run: echo "<<< main.py complete" 
        cd ./results
        git init
        git config --local user.name "${GITHUB_ACTOR}"
        export remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
        git add *.json
        git commit -m "Updated Citation Data"
        git push "${remote_repo}" HEAD:google-scholar-stats --force
    
